/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-Simple-SQLite-Client.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : Simple SQLite Client
 #	author : miyako
 #	2020/03/03
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-Simple-SQLite-Client.h"

#include "sqlite3.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- Simple SQLite Client
            
			case 1 :
				SQLite_EXECUTE(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void SQLite_EXECUTE(PA_PluginParameters params) {

  try {

    PackagePtr pParams = (PackagePtr)params->fParameters;

    C_TEXT Param1;
    Param1.fromParamAtIndex(pParams, 1);
    
    C_TEXT Param2;
    Param2.fromParamAtIndex(pParams, 2);
    
    CUTF8String fileName;
    Param1.copyPath(&fileName);
    
    CUTF8String sql;
    Param2.copyUTF8String(&sql);
    
    PA_CollectionRef Param3_params = PA_GetCollectionParameter(params, 3);
    
    C_LONGINT Param4;
    Param4.fromParamAtIndex(pParams, 4);
    
    integer_format_t integer_format = (integer_format_t)Param4.getIntValue();
    
    PA_ObjectRef returnValue = PA_CreateObject();
    
    unsigned int paramCount = 0;
    
    if(Param3_params) {
        paramCount = PA_GetCollectionLength(Param3_params);
    }
    
    bool useParams = (paramCount > 0);
    
    sqlite3 *pDb = NULL;
    
    int err = sqlite3_open((const char *)fileName.c_str(), &pDb);
    
    if(err == SQLITE_OK)
    {
        sqlite3_stmt *stmt = NULL;
        
        err = sqlite3_prepare_v2(pDb,
                                 (const char *)sql.c_str(),
                                 (int)sql.length(), &stmt, NULL);
        if(err == SQLITE_OK)
        {
            if(useParams) {
               
                for(unsigned int i = 0; i < paramCount; ++i) {
                    
                    PA_Variable v = PA_GetCollectionElement(Param3_params, i);
                    
                    PA_VariableKind kind = PA_GetVariableKind(v);
                    
                    switch (kind) {
                        case eVK_Unistring:
                        {
                            PA_Unistring u = PA_GetStringVariable(v);
                            
                            C_TEXT t;
                            t.setUTF16String((const PA_Unichar *)u.fString, u.fLength);
                            CUTF8String u8;
                            t.copyUTF8String(&u8);
                            
                            /* SQLITE_TRANSIENT tells sqlite3 to copy the bytes now;
                               u8 is a stack-local that goes out of scope before
                               sqlite3_step() runs, so NULL (== SQLITE_STATIC) here
                               would leave the bound value pointing at freed memory. */
                            sqlite3_bind_text(stmt, i + 1,
                                              (const char *)u8.c_str(), (int)u8.length(),
                                              SQLITE_TRANSIENT);
                            
                        }
                            break;
                        case eVK_Real:
                        {
                            double r = PA_GetRealVariable(v);
                            sqlite3_bind_double(stmt, i + 1, r);
                        }
                            break;
                        case eVK_Time:
                        {
                            PA_long32 t = PA_GetTimeVariable(v);
                            sqlite3_bind_int(stmt, i + 1, t);
                        }
                            break;
                        case eVK_Longint:
                        {
                            PA_long32 t = PA_GetLongintVariable(v);
                            sqlite3_bind_int(stmt, i + 1, t);
                        }
                            break;
                        case eVK_Null:
                        {
                            sqlite3_bind_null(stmt, i + 1);
                        }
                            break;
                        case eVK_Boolean:
                        {
                            char b = PA_GetBooleanVariable(v);
                            sqlite3_bind_int(stmt, i + 1, b);
                        }
                            break;
                        default:
                            break;
                    }
                }/* paramCount */
            }
            
            time_t startTime = time(0);
            
            PA_long32 r = 0;
            
            PA_CollectionRef resultRows = PA_CreateCollection();
            
            while(SQLITE_ROW == (err = sqlite3_step(stmt)))
            {
                time_t now = time(0);
                time_t elapsedTime = abs(startTime - now);
                
                if(elapsedTime > 0)
                {
                    startTime = now;
                    PA_YieldAbsolute();
                }
                
                PA_ObjectRef resultRow = PA_CreateObject();
                
                for(unsigned int i = 0; i < sqlite3_column_count(stmt); ++i) {
                    
                    int type = sqlite3_column_type(stmt, i);
                    const char * fieldName = sqlite3_column_name(stmt, i);
                    
                    switch (type) {
                                                        
                        case SQLITE_INTEGER:
                        {
                            int intValue = sqlite3_column_int(stmt, i);
                            
                            switch (integer_format) {
                                case integer_format_complex:
                                {
                                    sqlite3_int64 int64Value = sqlite3_column_int64(stmt, i);
                                    
                                    PA_ObjectRef resultCell = PA_CreateObject();
                                    ob_set_n(resultCell, L"intValue", intValue);
                                    
                                    /* INT64_MIN ("-9223372036854775808") is 20 characters
                                       and needs a 21st byte for the null terminator; a
                                       20-byte buffer overflows by one byte for that value. */
                                    std::vector<char> buf(21);
                                    memset((char *)&buf[0], 0, buf.size());
#if VERSIONMAC
                                    snprintf((char *)&buf[0], buf.size(), "%lld", int64Value);
#else
                                    sprintf_s((char *)&buf[0], buf.size(), "%lld", int64Value);
#endif
                                    ob_set_s(resultCell, L"int64Value", &buf[0]);
                                    
                                    ob_set_o(resultRow, fieldName, resultCell);
                                }
                                    break;
                                    
                                default:
                                    ob_set_n(resultRow, fieldName, intValue);
                                    break;
                            }
                        }
                            break;
                        case SQLITE_FLOAT:
                        {
                            double fieldValue = sqlite3_column_double(stmt, i);
                            ob_set_n(resultRow, fieldName, fieldValue);
                        }
                            break;
                        case SQLITE_TEXT:
                        {
                            const char *fieldValue = (const char *)sqlite3_column_text(stmt, i);
                            ob_set_s(resultRow, fieldName, fieldValue);
                        }
                            break;
                        case SQLITE_BLOB:
                        {
                            const void *fieldValue = sqlite3_column_blob(stmt, i);
                            int fieldLength = sqlite3_column_bytes(stmt, i);
                            
                            C_BLOB data;
                            data.setBytes((const uint8_t *)fieldValue, fieldLength);
                            
                            C_TEXT t;
                            data.toB64Text(&t);
                            
                            CUTF16String u16;
                            t.copyUTF16String(&u16);
                            
                            PA_ObjectRef resultCell = PA_CreateObject();
                            ob_set_a(resultCell, L"data", &u16);
                            
                            ob_set_o(resultRow, fieldName, resultCell);
                            
                        }
                            break;
                        case SQLITE_NULL:
                        {
                            ob_set_0(resultRow, fieldName);
                        }
                            break;
                        default:
                            break;
                    }
                    
                }
                
                PA_Variable v = PA_CreateVariable(eVK_Object);
                PA_SetObjectVariable(&v, resultRow);
                PA_SetCollectionElement(resultRows, r, v);
                
                r++;
            }

            ob_set_c(returnValue, L"values", resultRows);
            
            /* sqlite3_step() leaves the loop on anything other than SQLITE_ROW.
               SQLITE_DONE means the query ran to completion; any other code
               (e.g. SQLITE_ERROR, SQLITE_BUSY) means it stopped partway through
               and resultRows above is a truncated/partial result — surface that
               instead of silently reporting it as if it succeeded. */
            if(err != SQLITE_DONE) {
                ob_set_n(returnValue, L"error", err);
            }
            
            sqlite3_finalize(stmt);
        }else{
            ob_set_n(returnValue, L"error", err);
        }
        /* sqlite3_close() is always safe to call here even when prepare failed:
           sqlite3_open() populates pDb whether or not it returns SQLITE_OK. */
        sqlite3_close(pDb);
    }else{
        /* sqlite3_open()'s own documented contract: pDb is valid (if unusable)
           even on a non-OK return, and must still be released via sqlite3_close()
           to avoid leaking the connection object. sqlite3_close(NULL) is a
           documented no-op, so this is safe even in the rare case pDb is NULL. */
        ob_set_n(returnValue, L"error", err);
        sqlite3_close(pDb);
    }
    
    PA_ReturnObject(params, returnValue);

  } catch(...) {
      /* The manifest declares this command with a return type (:J), so 4D is
         waiting for PA_ReturnObject regardless of how execution ends. Letting
         an exception escape to PluginMain's catch(...) would swallow it
         without ever calling PA_ReturnObject, freezing the host. */
      PA_ObjectRef errorValue = PA_CreateObject();
      ob_set_n(errorValue, L"error", -1);
      PA_ReturnObject(params, errorValue);
  }
}

