/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Simple-SQLite-Client.h
 #	source generated by 4D Plugin Wizard
 #	Project : Simple SQLite Client
 #	author : miyako
 #	2020/03/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SIMPLE_SQLITE_CLIENT_H
#define PLUGIN_SIMPLE_SQLITE_CLIENT_H

#include "4DPluginAPI.h"

#include "C_LONGINT.h"
#include "C_TEXT.h"
#include "C_BLOB.h"

#include "4DPlugin-JSON.h"

#pragma mark -

void SQLite_EXECUTE(PA_PluginParameters params);

typedef enum {
 
    integer_format_simple = 0,
    integer_format_complex = 1
    
}integer_format_t;

#endif /* PLUGIN_SIMPLE_SQLITE_CLIENT_H */
